name: android-apk

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'   # зафиксированная версия
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Get packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug -v

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: FocusFlow-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
